### ISSUE TITLE
Unknown option mgshared

### ISSUE THREAD

**Issue by boe007** [Kwyrky/MonoGame.Kickstarter#1]
Hello,

I want to create a shared library project (for a dll) with the kickstarter, but the bash says: Unknown option -- mgshared

![image](https://user-images.githubusercontent.com/5685366/95965977-e20e9380-0e0a-11eb-96f7-6ee759e11c81.png)

**Comment by Kwyrky** [comment]
The script supports only DesktopGL, WindowsDX and Android (manual steps necessary).
