### ISSUE TITLE
iOS project doesn't get Generated

### ISSUE THREAD

**Issue by javierpal** [Kwyrky/MonoGame.Kickstarter#4]
When  trying to generate the iOS project, it doesn't get generated here are a screenshot.

![image](https://github.com/Kwyrky/MonoGame.Kickstarter/assets/11380922/23500d04-8fec-453e-9500-4e318870fa65)

there are some error on the generated solutions too.

![image](https://github.com/Kwyrky/MonoGame.Kickstarter/assets/11380922/4a15b0ff-c723-496c-99de-45d13878b2a1)

**Comment by Kwyrky** [comment]
Hi, iOS is not supported. I have no time to work on the project at the moment unfortunately.
